name: Run on push checks
on:
  push:
jobs:
  on-push-workflow:
    uses: ./.github/workflows/tre-github-actions-on-push.yml
    with:
      run_unit_tests: true
      run_feature_tests: true
      run_pre_commit: true
