name: Run on push checks
on:
  push:
jobs:
  on-push-workflow:
    uses: nationalarchives/tre-github-actions/.github/workflows/tre-fn-checks.yml@0.0.5
    with:
      run_unit_tests: True
      run_feature_tests: True
      run_pre_commit: True
