name: Run on push checks
on:
  push:
jobs:
  on-push-workflow:
    uses: nationalarchives/da-tre-github-actions/.github/workflows/tre-fn-checks.yml@0.0.6
    with:
      run_unit_tests: True
      run_feature_tests: True
      run_pre_commit: True
      requirements_txt: tre-bagit-to-dri-sip/requirements.txt
    secrets:
      AWS_OPEN_ID_CONNECT_ROLE_ARN: ${{ secrets.AWS_OPEN_ID_CONNECT_ROLE_ARN }}
      AWS_CODEARTIFACT_REPOSITORY_NAME: ${{ secrets.AWS_CODEARTIFACT_REPOSITORY_NAME }}
      AWS_CODEARTIFACT_REPOSITORY_DOMAIN: ${{ secrets.AWS_CODEARTIFACT_REPOSITORY_DOMAIN }}
      AWS_CODEARTIFACT_REPOSITORY_ACCOUNT: ${{ secrets.AWS_CODEARTIFACT_REPOSITORY_ACCOUNT }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
