name: Run tests

on:
  push:
#  pull_request:
#    branches:
#      - main

jobs:
  check-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Run unit tests
        shell: bash
        run: |
          cd tests/units
          python -m unittest discover
  check-feature-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Run feature tests
        shell: bash
        run: |
          pip install behave
          cd tests
          behave
  check-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Run pre-commit
        shell: bash
        run: |
          pip install pre-commit
          pre-commit --version
          pre-commit install
          pre-commit run --all-files
