name: Run tests

on:
  push:
#  pull_request:
#    branches:
#      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Run unit tests
        shell: bash
        run: |
          echo "Local file listing follows:"
          ls -la
          cd tests/units
          pwd
          ls -la
          python -m unittest discover
